services:
  postgres:
    container_name: Test
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cafe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
volumes:
  postgres-data:
